[workspace]
channels = ["conda-forge"]
name = "DiffCLR"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
tiktok = "python main.py -c conf/tiktok.toml"
yelp = "python main.py -c conf/yelp.toml"
sports = "python main.py -c conf/sports.toml"

[system-requirements]
cuda = "11"
libc = { family = "glibc", version = "2.27" }

[environments]
default = {features = ["default"], solve-group = "prod"}
dev = {features = ["default", "dev"], solve-group = "prod"}

[dependencies]
python = "==3.10.16"
pytorch-gpu = "==1.12.1"
cudatoolkit = "==11.3.1"
toml = ">=0.10.2,<0.11"
numpy = "==1.21.6"

[pypi-dependencies]
safetensors = "==0.5.3"
scikit-learn = "==1.4.0"
scipy = "==1.9.1"

[feature.dev.pypi-dependencies]
matplotlib = "==3.8"
ipykernel = "*"

[feature.dev.dependencies]
pandas = ">=2.0.3,<3"
nvitop = ">=1.5.3,<2"
